# Generated by Django 2.0.2 on 2018-08-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_runddos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliEcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('ip', models.CharField(max_length=200, verbose_name='ip')),
            ],
            options={
                'verbose_name': '阿里ecs服务器',
                'verbose_name_plural': '阿里ecs服务器',
            },
        ),
        migrations.CreateModel(
            name='AliKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ak_id', models.CharField(max_length=200, verbose_name='id')),
                ('ak_secret', models.CharField(max_length=200, verbose_name='key密码')),
            ],
            options={
                'verbose_name': '阿里key',
                'verbose_name_plural': '阿里key',
            },
        ),
    ]
