# Generated by Django 2.0.2 on 2018-08-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_aliecs_alikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='alikey',
            name='security_group_id',
            field=models.CharField(default='', max_length=200, verbose_name='安全组'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alikey',
            name='vswitch_id',
            field=models.CharField(default='', max_length=200, verbose_name='vswitch'),
            preserve_default=False,
        ),
    ]
