# Generated by Django 2.0.2 on 2018-08-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20180825_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='alikey',
            name='aliyun_images',
            field=models.CharField(default='', max_length=200, verbose_name='aliyun初始化镜像'),
            preserve_default=False,
        ),
    ]
