# Generated by Django 2.0.2 on 2018-09-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_accessrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliJenkins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=200, verbose_name='jobname')),
                ('Branchname', models.CharField(max_length=200, verbose_name='分支名')),
            ],
            options={
                'verbose_name': '阿里cd自动构建',
                'verbose_name_plural': '阿里cd自动构建',
            },
        ),
    ]
