# Generated by Django 2.0.1 on 2018-09-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alijenkins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jiankong_leixing', models.CharField(max_length=200, verbose_name='监控类型')),
                ('renwu_mingcheng', models.CharField(max_length=200, verbose_name='任务名称')),
                ('jiankong_dizhi', models.CharField(max_length=200, verbose_name='监控地址')),
                ('jiankong_pinlv', models.CharField(max_length=200, verbose_name='监控频率')),
                ('keyongxing', models.CharField(max_length=200, verbose_name='可用性')),
                ('pinjun_shijian', models.CharField(max_length=200, verbose_name='平均响应时间')),
                ('lianxu_yuzhi_baojing', models.CharField(max_length=200, verbose_name='连续阈值后报警')),
                ('baojing_jibie', models.CharField(max_length=200, verbose_name='报警级别')),
            ],
            options={
                'verbose_name': '站点管理',
                'verbose_name_plural': '站点管理',
            },
        ),
        migrations.CreateModel(
            name='Yunwei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XingMing', models.CharField(max_length=200, verbose_name='姓名')),
                ('shouji_haoma', models.CharField(max_length=200, verbose_name='手机号码')),
                ('youxiang', models.CharField(max_length=200, verbose_name='邮箱')),
                ('wangwang', models.CharField(max_length=200, verbose_name='旺旺')),
                ('dingding', models.CharField(max_length=200, verbose_name='钉钉')),
            ],
            options={
                'verbose_name': '报警联系人',
                'verbose_name_plural': '报警联系人',
            },
        ),
        migrations.CreateModel(
            name='YunweiZu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XingMing', models.CharField(max_length=200, verbose_name='组名')),
                ('shouji_haoma', models.CharField(max_length=200, verbose_name='备注')),
                ('youxiang', models.CharField(max_length=200, verbose_name='联系人')),
                ('wangwang', models.CharField(max_length=200, verbose_name='旺旺')),
                ('dingding', models.CharField(max_length=200, verbose_name='钉钉')),
            ],
            options={
                'verbose_name': '报警联系人',
                'verbose_name_plural': '报警联系人',
            },
        ),
        migrations.AddField(
            model_name='yunwei',
            name='yunweizu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.YunweiZu', verbose_name='所属组'),
        ),
    ]
