# Generated by Django 2.0.1 on 2018-09-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20180914_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='XiangyingShijian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns', models.CharField(max_length=200, verbose_name='dns时间')),
                ('jianlian', models.CharField(max_length=200, verbose_name='建连时间')),
                ('chongDingxiang', models.CharField(max_length=200, verbose_name='重定向时间')),
                ('ShoubaoShijian', models.CharField(max_length=200, verbose_name='首包时间')),
                ('ZhunbeiShijian', models.CharField(max_length=200, verbose_name='准备时间')),
                ('SSL', models.CharField(max_length=200, verbose_name='SSL时间')),
            ],
            options={
                'verbose_name': '指标对比',
                'verbose_name_plural': '指标对比',
            },
        ),
        migrations.CreateModel(
            name='zhujiJiankong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='主机名')),
                ('ip', models.CharField(max_length=200, verbose_name='ip')),
                ('cpu', models.CharField(max_length=200, verbose_name='cpu')),
                ('mem', models.CharField(max_length=200, verbose_name='内存')),
                ('disk', models.CharField(max_length=200, verbose_name='磁盘')),
            ],
            options={
                'verbose_name': '主机监控',
                'verbose_name_plural': '主机监控',
            },
        ),
    ]
