# Generated by Django 2.0.2 on 2018-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20180919_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alifee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='用户名')),
                ('amount', models.CharField(max_length=8000, verbose_name='余额')),
            ],
            options={
                'verbose_name': '阿里key',
                'verbose_name_plural': '阿里key',
            },
        ),
        migrations.AddField(
            model_name='alikey',
            name='fee',
            field=models.CharField(default='', max_length=8000, verbose_name='余额'),
            preserve_default=False,
        ),
    ]
