# Generated by Django 2.0.2 on 2018-09-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20180919_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='alifee',
            name='date',
            field=models.DateField(),
#            preserve_default=False,
        ),
    ]
