# Generated by Django 2.0.2 on 2018-09-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20180919_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alifee',
            name='amount',
            field=models.CharField(max_length=200, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='alilaxin',
            name='daiLi',
            field=models.CharField(max_length=200, verbose_name='代理'),
        ),
        migrations.AlterField(
            model_name='alilaxin',
            name='orderId',
            field=models.CharField(max_length=200, verbose_name='首购订单'),
        ),
        migrations.AlterField(
            model_name='alilaxin',
            name='status',
            field=models.CharField(max_length=2000, verbose_name='用户状态'),
        ),
    ]
