# Generated by Django 2.0.2 on 2018-09-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20180919_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anhui', models.CharField(max_length=200, verbose_name='安徽')),
                ('jiangxi', models.CharField(max_length=200, verbose_name='江西')),
                ('zhejiang', models.CharField(max_length=200, verbose_name='浙江')),
                ('chongqing', models.CharField(max_length=200, verbose_name='重庆')),
                ('sichuan', models.CharField(max_length=200, verbose_name='四川')),
                ('shandong', models.CharField(max_length=200, verbose_name='山东')),
                ('fujian', models.CharField(max_length=200, verbose_name='福建')),
                ('hubei', models.CharField(max_length=200, verbose_name='湖北')),
                ('hainan', models.CharField(max_length=200, verbose_name='海南')),
                ('yunan', models.CharField(max_length=200, verbose_name='云南')),
                ('jiangsu', models.CharField(max_length=200, verbose_name='江苏')),
                ('hebei', models.CharField(max_length=200, verbose_name='河北')),
                ('shanxi', models.CharField(max_length=200, verbose_name='陕西')),
                ('tianjin', models.CharField(max_length=200, verbose_name='天津')),
            ],
            options={
                'verbose_name': '阿里key',
                'verbose_name_plural': '阿里key',
            },
        ),
    ]
