# Generated by Django 2.0.2 on 2018-09-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20180919_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliboard',
            name='mydate',
            field=models.DateTimeField(),
            #preserve_default=False,
        ),
    ]
