# Generated by Django 2.0.2 on 2018-09-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_aliboard_mydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliboard',
            name='mydate',
            field=models.DateTimeField(verbose_name='日期'),
        ),
    ]
