# Generated by Django 2.0.2 on 2018-09-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20180920_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='chixujiaofu',
            name='git',
            field=models.CharField(default='', max_length=200, verbose_name='git地址'),
            preserve_default=False,
        ),
    ]
