# Generated by Django 2.0.2 on 2018-09-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_chixujiaofu_git'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rundocker',
            options={'verbose_name': 'pod', 'verbose_name_plural': 'pod'},
        ),
        migrations.AddField(
            model_name='rundocker',
            name='tag',
            field=models.CharField(default='', max_length=200, verbose_name='tag'),
            preserve_default=False,
        ),
    ]
