# Generated by Django 2.0.2 on 2018-09-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20180927_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundocker',
            name='env',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='环境变量'),
        ),
        migrations.AlterField(
            model_name='rundocker',
            name='liveness',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='liveness'),
        ),
        migrations.AlterField(
            model_name='rundocker',
            name='readiness',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='readiness'),
        ),
    ]
