# Generated by Django 2.0.2 on 2018-09-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20180927_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundocker',
            name='port',
            field=models.CharField(default='80', max_length=200, null=True, verbose_name='liveness'),
        ),
    ]
